apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ayazlogistics-rules
  namespace: lgtm-stack
spec:
  groups:
  - name: ayazlogistics.rules
    rules:
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High error rate detected"
        description: "Error rate is {{ $value }} errors per second"

    - alert: HighResponseTime
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High response time detected"
        description: "95th percentile response time is {{ $value }} seconds"

    - alert: HighCPUUsage
      expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected"
        description: "CPU usage is {{ $value }}%"

    - alert: HighMemoryUsage
      expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage detected"
        description: "Memory usage is {{ $value }}%"

    - alert: DatabaseConnectionFailure
      expr: up{job="postgresql"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Database connection failed"
        description: "PostgreSQL database is not responding"

    - alert: RedisConnectionFailure
      expr: up{job="redis"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Redis connection failed"
        description: "Redis cache is not responding"

    - alert: DiskSpaceLow
      expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Disk space low"
        description: "Disk usage is {{ $value }}%"

    - alert: PodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Pod crash looping"
        description: "Pod {{ $labels.pod }} is crash looping"

    - alert: DBPoolSaturationHigh
      expr: avg_over_time(db_pool_in_use_connections[5m]) / avg_over_time(db_pool_max_connections[5m]) > 0.85
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "Database pool saturation high"
        description: "DB pool usage >85% for 10m"

    - alert: APIErrorRateHigh
      expr: rate(http_requests_total{status=~"5.."}[10m]) / rate(http_requests_total[10m]) > 0.05
      for: 10m
      labels:
        severity: critical
      annotations:
        summary: "API 5xx error rate high"
        description: "5xx ratio >5% for 10m"