_format_version: "3.0"

services:
  - name: ayazlogistics-backend
    url: http://backend:3000
    routes:
      - name: auth-routes
        paths:
          - /api/v1/auth
        strip_path: false
        methods:
          - GET
          - POST
        plugins:
          - name: rate-limiting
            config:
              minute: 20
              policy: local

      - name: tms-routes
        paths:
          - /api/v1/tms
        strip_path: false
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        plugins:
          - name: jwt
            config:
              secret_is_base64: false
          - name: rate-limiting
            config:
              minute: 100
              hour: 5000
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - PUT
                - DELETE
              headers:
                - Authorization
                - Content-Type
              credentials: true

plugins:
  - name: prometheus
    config:
      per_consumer: true

  - name: request-transformer
    config:
      add:
        headers:
          - "X-Gateway-Version:1.0"

  - name: response-transformer
    config:
      add:
        headers:
          - "X-Powered-By:AyazLogistics"

