apiVersion: v1
kind: Service
metadata:
  name: ayazlogistics-backend
  namespace: production
  labels:
    app: ayazlogistics
    component: backend
spec:
  selector:
    app: ayazlogistics
    component: backend
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
